### ISSUE TITLE
http service wrapper -- errors when integrate

### ISSUE THREAD

**Issue by denishaskin** [neroniaky/angular-token#288]
I have working API calls without using `angular2-token`'s HTTP service wrapper:

```
export class ValService {
  private backendUrl = environment.apiBase;  // URL to web API

  constructor (private http: Http) {}

  getTerms(params:any): Observable<ResultSet<Term>> {
  ...irrelevant details omitted...
    return this.http.get(this.backendUrl + '/terms', requestOptions)
                    .map(this.extractData)
                    .catch(this.handleError);
  }

```

but when I swap in the service wrapper:

```
export class ValService {
  constructor (
    private tokenService: Angular2TokenService) {}

  getTerms(params:any): Observable<ResultSet<Term>> {
  ...irrelevant details omitted...
    return this.tokenService.get('/terms', requestOptions)
                    .map(this.extractData)
                    .catch(this.handleError);
  }
```

I get puzzling errors (no back-end request is getting fired):

```
VM6870:27 EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: Cannot read property 'toUpperCase' of undefined
Error: Error in :0:0 caused by: Cannot read property 'toUpperCase' of undefined
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7271:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:31160:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:31225:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:62352:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:85778:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:85751:18)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:63279:20)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:68787:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:25993:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:25960:26)
    at http://localhost:4200/vendor.bundle.js:25896:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:25896:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:25870:14)
    at http://localhost:4200/vendor.bundle.js:25431:22
```

Thoughts?

**Comment by denishaskin** [comment]
For the time being I'm working around this with:

```
  getTerms(params:any): Observable<ResultSet<Term>> {
      ...
    let requestOptions = this.defaultRequestOptions();
      ...
    return this.http.get(this.backendUrl + '/terms', requestOptions)
                    .map(this.extractData)
                    .catch(this.handleError);
  }

...

  private defaultRequestOptions(): RequestOptions {
    return new RequestOptions({headers: this.tokenService.currentAuthHeaders});
  }

```

**Comment by neroniaky** [comment]
Please migrate to version 7.x. This problem should be fixed with the use of interceptors. Please reopen if it isn't. Thanks!
